const WorkOrders = [{
    status: 'Draft',
    service_date: '6/30/2016',
    service_time: '2:17 PM',
    title: 'Alarm system false reporting due to possible keypad< water damage',
    address1: '6556 Evergreen Boulevard Apt 76',
    address2: 'Royalston, MA 01368',
    pay_type: 'hourly',
    pay_amount: 12,
    id: '46',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Draft',
    service_date: '6/30/2016',
    service_time: '1:47 PM',
    title: 'POS unit printing multiple copies of send receipts',
    address1: '6368 7th Circle Suite 69',
    address2: 'Jamestown, MI 49427',
    pay_type: 'hourly',
    pay_amount: 8,
    id: '47',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Draft',
    service_date: '6/30/2016',
    service_time: '1:17 PM',
    title: 'Install new POS unit at regional store location',
    address1: '4816 Meadow Ave Unit 83',
    address2: 'Omaha, NE 68110',
    pay_type: 'hourly',
    pay_amount: 10,
    id: '48',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Draft',
    service_date: '6/30/2016',
    service_time: '12:47 PM',
    title: 'Install new POS unit at regional store location',
    address1: '934 Laurel Field Apt 29',
    address2: 'Bancroft, WI 54921',
    pay_type: 'hourly',
    pay_amount: 10,
    id: '49',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Draft',
    service_date: '6/30/2016',
    service_time: '1:47 PM',
    title: 'Repair broken sill near the south west office possible water damage due to rain',
    address1: '4279 Dogwood Cove Unit 39',
    address2: 'Purcellville, VA 20132',
    pay_type: 'hourly',
    pay_amount: 9,
    id: '50',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Published',
    service_date: '6/30/2016',
    service_time: '1:47 PM',
    title: 'Alarm system false reporting due to possible keypad water damage',
    address1: '3572 Lincoln Loop Ste 47',
    address2: 'Fort Mc Kavett, TX 76841',
    pay_type: 'hourly',
    pay_amount: 15,
    id: '52',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Published',
    service_date: '6/30/2016',
    service_time: '2:17 PM',
    title: 'Site survey for RJ-45 install project across entire store follow layout as per instructions',
    address1: '4601 Ninth Field Apt 56',
    address2: 'Concord, CA 94521',
    pay_type: 'hourly',
    pay_amount: 9,
    id: '54',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Published',
    service_date: '6/30/2016',
    service_time: '11:47 AM',
    title: 'CCTV display replacement MUST BE DONE BY WEDNESDAY',
    address1: '3983 Fifth Loop Suite 55',
    address2: 'Roach, MO 65787',
    pay_type: 'hourly',
    pay_amount: 12,
    id: '55',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Routed',
    service_date: '6/30/2016',
    service_time: '1:47 PM',
    title: 'Flood caused water damage to CCTV unit in rear office',
    address1: '5583 Evergreen Arcade Suite 38',
    address2: 'Abilene, TX 79699',
    pay_type: 'hourly',
    pay_amount: 13,
    id: '56',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Work Done',
    service_date: '6/30/2016',
    service_time: '2:00 PM',
    title: 'Broken CCTV display - replace as per on site contaxt',
    address1: '4208 Sunset Beach Apt 1',
    address2: 'Newton Lower Falls, MA 02462',
    pay_type: 'hourly',
    pay_amount: 10,
    id: '57',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Routed',
    service_date: '6/30/2016',
    service_time: '1:17 PM',
    title: 'Site survey for RJ-45 install project across entire store follow layout as per instructions',
    address1: '1354 4th Garden Suite 41',
    address2: 'Lizemores, WV 25125',
    pay_type: 'hourly',
    pay_amount: 12,
    id: '58',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Published',
    service_date: '6/30/2016',
    service_time: '12:47 PM',
    title: 'Replace CCTV unit - currently has broken cabling due to unknown damage',
    address1: '4121 4th Estate Apt 91',
    address2: 'Port Byron, IL 61275',
    pay_type: 'hourly',
    pay_amount: 13,
    id: '60',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Published',
    service_date: '6/30/2016',
    service_time: '2:47 PM',
    title: 'Alarm system false reporting due to possible keypad water damage',
    address1: '9572 Church Hill Ste 51',
    address2: 'Newbury Park, CA 91319',
    pay_type: 'hourly',
    pay_amount: 10,
    id: '61',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Published',
    service_date: '6/30/2016',
    service_time: '1:47 PM',
    title: 'Site survey for RJ-45 install project across entire store follow layout as per instructions',
    address1: '6615 Birch Bluff Unit 15',
    address2: 'Burns, KS 66840',
    pay_type: 'hourly',
    pay_amount: 15,
    id: '62',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Published',
    service_date: '6/30/2016',
    service_time: '12:17 PM',
    title: 'Broken CCTV display - replace as per on site contaxt',
    address1: '4243 Jackson Circle Apt 86',
    address2: 'Troy, IN 47588',
    pay_type: 'hourly',
    pay_amount: 10,
    id: '63',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Assigned',
    service_date: '6/30/2016',
    service_time: '2:47 PM',
    title: 'Fire damage on alarm system due to water damage',
    address1: '3010 4th Avenue Unit 45',
    address2: 'Alberta, MN 56207',
    pay_type: 'hourly',
    pay_amount: 15,
    id: '64',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Assigned',
    service_date: '6/30/2016',
    service_time: '2:17 PM',
    title: 'Register not printing receipts anymore even though paper is loaded',
    address1: '9675 4th Field Ste 50',
    address2: 'Saint Albans, MO 63073',
    pay_type: 'hourly',
    pay_amount: 10,
    id: '65',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Assigned',
    service_date: '6/30/2016',
    service_time: '2:17 PM',
    title: 'Replace broken CCTV display at site NO LATER THAN 5pm',
    address1: '286 Main Circle Unit 5',
    address2: 'Cheriton, VA 23316',
    pay_type: 'hourly',
    pay_amount: 14,
    id: '66',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Assigned',
    service_date: '6/30/2016',
    service_time: '12:17 PM',
    title: 'ATM service repair keypad replacement damaged due to water leakage from overhead A/C system',
    address1: '1310 Jackson Expy Unit 87',
    address2: 'Foxboro, MA 02035',
    pay_type: 'hourly',
    pay_amount: 9,
    id: '67',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Assigned',
    service_date: '6/30/2016',
    service_time: '2:47 PM',
    title: 'Replace broken keypad unit on alarm near south wall MUST BE PERFORMED TUESDAY',
    address1: '3458 Delaware Pkwy Suite 76',
    address2: 'Walnut Cove, NC 27052',
    pay_type: 'hourly',
    pay_amount: 15,
    id: '68',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Assigned',
    service_date: '6/30/2016',
    service_time: '2:17 PM',
    title: 'Install new POS unit at regional store location',
    address1: '5335 3rd Estate Suite 38',
    address2: 'Akron, OH 44315',
    pay_type: 'hourly',
    pay_amount: 12,
    id: '69',
    project: 'Broken CCTV display - replace as per on site contaxt'
}, {
    status: 'Work Done',
    service_date: '6/30/2016',
    service_time: '1:17 PM',
    title: 'Verify theft of main device due to chain',
    address1: '5005 Park Dr Suite 79',
    address2: 'Chicago, IL 60685',
    pay_type: 'hourly',
    pay_amount: 13,
    id: '70',
    project: 'Broken CCTV display - replace as per on site contaxt'
}];

export default WorkOrders;